---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true
install_zsh_plugins: true
configure_zshrc: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- 'App Store'
- Calendar
- Contacts
- FaceTime
- Freeform
- Maps
- Music
- Podcasts
- TV
dockitems_persist:
- name: "Brave Browser"
  path: "/Applications/Brave Browser.app/"
  pos: 2
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 9
- name: "PyCharm"
  path: "/Applications/PyCharm CE.app/"
  pos: 10
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 11
- name: "Activity Monitor"
  path: "/Applications/Utilities/Activity Monitor.app/"
  pos: 12
- name: "Notion"
  path: "/Applications/Notion.app/"
  pos: 13
- name: "Signal"
  path: "/Applications/Signal.app/"



configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ppiekars/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .osx

homebrew_installed_packages:
  # - gh
  # - gpg
  # - hadoop
  # - httpie
  - kubernetes-cli
  # - msodbcsql18
  # - mssql-tools18
  # - unixodbc
  - node
  - pnpm
  - pre-commit
  - openssl
  - pyenv
  # - snappy
  - sqlite
  - uv
  - wget



homebrew_taps:
  - homebrew/core
  - homebrew/cask
  # - microsoft/mssql-release

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - adobe-acrobat-reader
  - aldente
  - altserver
  - alt-tab
  - docker
  # - google-chrome
  - brave-browser
  # - hot
  - iterm2
  # - microsoft-azure-storage-explorer
  # - microsoft-remote-desktop
  - nextcloud
  # - notion
  # - postman
  # - pycharm
  - pycharm-ce
  - rectangle
  - signal
  - discord
  - teamviewer
  - transmission
  - tor-browser
  - visual-studio-code
  - vlc
  - wine-stable


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


# Default theme
oh_my_zsh_theme: "powerlevel10k/powerlevel10k"

# Default plugins
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# Whether to install by default for all specified users.
# May be overridden by `oh_my_zsh: install:` under each user.
oh_my_zsh_install: true

# Default update mode for Oh-My-Zsh
# accepted values are:
# disabled (default)
# auto
# reminder
oh_my_zsh_update_mode: reminder

# Default update frequency in days. When the update mode is set to a value other
# than "disabled", this is the frequency (in days) to check for a new version.
# The value 0 will check every time a new shell session starts.
oh_my_zsh_update_frequency: 13

# Whether to write the ~/.zshrc file
# May be overridden by `oh_my_zsh: write_zshrc:` under each user.
oh_my_zsh_write_zshrc: true
